# borrowed from https://cloud.weave.works/k8s/scope.yaml?k8s-version=1.10.0
apiVersion: apps/v1
kind: Deployment
metadata:
  name: uberkuber-app
  labels:
    name: uberkuber-app
    app: uberkuber
    weave-cloud-component: scope
    weave-scope-component: app
  namespace: weave
spec:
  replicas: 1
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        name: uberkuber-app
        app: uberkuber
        weave-cloud-component: scope
        weave-scope-component: app
    spec:
      containers:
        - name: app
          args:
            - '--no-probe'
          env: []
          image: weaveworks/scope:1.11.2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4040
              protocol: TCP
