# borrowed from https://cloud.weave.works/k8s/scope.yaml?k8s-version=1.10.0
apiVersion: v1
kind: Service
metadata:
  name: uberkuber-app
  labels:
    name: uberkuber-app
    app: uberkuber
    weave-cloud-component: scope
    weave-scope-component: app
  namespace: weave
spec:
  ports:
    - name: app
      port: 80
      protocol: TCP
      targetPort: 4040
  selector:
    name: uberkuber-app
    app: uberkuber
    weave-cloud-component: scope
    weave-scope-component: app
